### PR TITLE
AB#18 Update validationcode.py

### PR DESCRIPTION
**Pull request by m4rika22**

### CODE REVIEW

**Review by heidi-999 — CHANGES_REQUESTED** [review]
Please do something else, thanks.

**Review by heidi-999 — COMMENTED** [review]
Well done!

**Review by petra22002 — COMMENTED** [review]
fine it is good

**Review by heidi-999 — APPROVED** [review]

**Review by Linzku — APPROVED** [review]
Ok.

**Review by petra22002 — APPROVED** [review]

**Pull request merged**
