### PR TITLE
AB#19 Update FakeDatabase

### PR DESCRIPTION
**Pull request by petra22002**

### CODE REVIEW

**Review by petra22002 — COMMENTED** [review]
fine..

**Review by m4rika22 — COMMENTED** [review]
It's always nice to have +

**Review by Linzku — COMMENTED** [review]
Good.

**Review by heidi-999 — COMMENTED** [review]
Now it looks good.. I guess

**Review by heidi-999 — APPROVED** [review]

**Review by m4rika22 — APPROVED** [review]
Nice

**Pull request merged**
